# Generated by Django 5.0.6 on 2024-07-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUIZ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='correct_option',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
